import {config,vault} from './security.mjs';
import {Store} from './store.mjs';
import {GoogleCalendar} from './google.mjs';
import {BookingService} from './service.mjs';
import {makeServer} from './http.mjs';
import {BrevoClient,BrevoSync} from './brevo.mjs';
const settings=config(),store=new Store(settings.credentials);
const calendar=new GoogleCalendar(settings,store,vault(settings.encryptionKey));
const brevo=settings.brevoApiKey?new BrevoSync({store,client:new BrevoClient(settings.brevoApiKey),allowedEmails:settings.allowedEmails}):null;
const service=new BookingService({store,calendar,brevo,allowedEmails:settings.allowedEmails});
const server=makeServer({config:settings,store,calendar,service});
server.listen(settings.port,'0.0.0.0',()=>console.log('Protected staging server ready'));
const syncTimer=brevo?setInterval(()=>brevo.kick(),60000):null;
brevo?.kick();
process.on('SIGTERM',()=>{if(syncTimer)clearInterval(syncTimer);server.close(()=>process.exit(0));});
